### ISSUE TITLE
 How can I relate the actual_time to the call.

### ISSUE THREAD

**Issue by guinfox** [ticgal/actualtime#103]
<p><a href="https://github.com/ticgal/actualtime/issues/103">https://github.com/ticgal/actualtime/issues/103</a></p><p>Hi friends!</p><p>I'm using the query via metabase to be able to extract the data of the service time by technician. However, the glpi_plugin_actualtime_tasks table does not have a column that I can relate to the incident ID, only task. Could anyone tell which table holds the actual_time_ID that can be related to the Incident ID.</p><p><img src="https://user-images.githubusercontent.com/107438460/185725584-a059d1be-10d4-4afc-b4cf-11e4fd63af6e.png" alt="image" /></p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_10889' rel='nofollow'>10889</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by guinfox** [comment]
![image](https://user-images.githubusercontent.com/107438460/185725503-35300144-e166-4518-af6e-f7d899472678.png)

**Comment by OscarBeiro** [comment]
Hi,
Thanks for using ActualTime. Unfortunately, this is not a real issue.

You need to relate the actualtime id with the taskid , and the taskid with the ticketid. It is a simple SQL join, but completely out of the scope of the plugin.

Regards,
