### ISSUE TITLE
GLPI 10 Timer Not displayed even after adding Project Task

### ISSUE THREAD

**Issue by danisscenario** [ticgal/actualtime#108]
Per issues https://github.com/ticgal/actualtime/issues/107 i added a task  but the result is that there is still no button
I do apologize if project task isnt what is meant, in which case i would like to ask where in GLPI 10 is the task for ticket located. because the only material im finding for it is for earlier version of GLPI.
![Snímek obrazovky 2022-10-26 074929](https://user-images.githubusercontent.com/116552464/197949725-6a1134cd-d00f-4129-bd97-714b889362c9.jpg)

**Comment by fernandosantos96** [comment]
Hello,

You're not seeing a timer because you don't have any tasks in your ticket. For creating a new task you must use the  small arrow on the right of the yellow button in the bottom left of the ticket view and choose "Create a Task".

Regards
