### ISSUE TITLE
Time Recording Report

### ISSUE THREAD

**Issue by andersonrmartins** [ticgal/actualtime#112]
Desenvolvi uma Query para puxar relatório de apontamento de horas, seria muito bom se ele estivesse integrado ao Plugin
pois quem trabalha com Apontamento de Horas, provavelmente necessita de um relatório para verificar os apontamentos.
Se estiver interesse, gostaria de colaborar fornecendo a query para a implantação nas próximas versões

I developed a Query to pull a time report, it would be great if it were integrated into the Plugin
because whoever works with Hours, probably needs a report to verify the notes.
If you are interested, I would like to collaborate by providing the query for deployment in the next versions

**Comment by gitsyncuser** [comment]
<p>Olá Andersons,</p>\r\n<p>GLPI reporting capabilities are not very good.</p>\r\n<p>Maybe a Dashboard widget will be the best way to go. Please go ahead and share your SQL, or contribute with a new widget.</p>\r\n<p>Regards,</p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by alekyxander** [comment]
@andersonrmartins  poderia disponibilizar a consulta pra puxar o relatório?

**Comment by OscarBeiro** [comment]
Abandoned.
