### ISSUE TITLE
Unable to Add Solution - Mandatory fields : Duration

### ISSUE THREAD

**Issue by hsbsandrecv** [ticgal/actualtime#113]
GLPI 10.0.5
actualtime	2.0.0

Display pop-up window with current running timer: Yes
Display actual time in closed task box ('Processing ticket' list): Yes
Automatically open task with timer running: Yes
Automatically update the duration	: Yes

I noticed two things in 10.0.5/2.0.0 compared to the production in GLPI 9.5.11/actualtime  1.5.0.
In 9.5/1.5 when I stop the timer in the task it changes the task duration and set it to done.
in 10.0.5/2.0.0 It set the actual time, but leave the task in todo, and no duration.
Even changing manually the task to Done and setting a duration.

in the Todo List
Tasks
Total duration: 5 minutes 0 seconds
100%
no pending tasks

when adding a solution to the ticket we got this message

Mandatory fields : Duration

![image](https://user-images.githubusercontent.com/29098745/206556754-5c2ee1ef-8078-40f9-a0f5-7d7f4f9676e2.png)

**Comment by hsbsandrecv** [comment]
one thing that I just notice, 
Ticket Total Duration Field is available on Ticket Opening form, not after that
![image](https://user-images.githubusercontent.com/29098745/206786524-2589f49f-cd80-4bb0-b285-6c78b6afcc7e.png)

**Comment by hsbsandrecv** [comment]
sorry guys this "bug" is related to another plugin

https://plugins.glpi-project.org/#/plugin/moreticket

**Comment by OscarBeiro** [comment]
Thanks for the feedback.
