### ISSUE TITLE
15-Support Project task

### ISSUE THREAD

**Issue by gitsyncuser** [ticgal/actualtime#117]
<p>Support Project tasks with Actualtime to track spent management time</p><blockquote>Numero de la peticion de GLPI: <a href='https://xes.ticgal.com/index.php?redirect=ticket_15716' rel='nofollow'>15716</a><br>Creado por <a href='https://tic.gal'>GitSync</a> en GLPI por Xacobo Freire</blockquote>

**Comment by OscarBeiro** [comment]
Ready for 3.0.0.
