### ISSUE TITLE
Update Travis CI config and plugin compatibility

### ISSUE THREAD

**Issue by Multiconecta** [ticgal/actualtime#12]
Travis CI tests does not include PHP 7.3 branch and still includes unsupported Glpi 9.2 branch. Should be updated. For synchronizing code, setup.php should correctly enforce Glpi >= 9.3 on functions plugin_version_actualtime() and plugin_actualtime_check_prerequisites().

**Comment by OscarBeiro** [comment]
Obrigado @Multiconecta
