### ISSUE TITLE
button of Start Stop doesnt appear

### ISSUE THREAD

**Issue by osanchezctrl365service** [ticgal/actualtime#120]
I installed the plugin from the marketplace in the glpi 10.05 version, I have it configured to enable actualtime, but when I open a ticket to work as an assigned technician it does not show me the start and stop buttons, install the plugin from the marketplace in the glpi 10.05 version, I have it configured to enable actualtime, but when I open a ticket to work as an assigned technician, it does not show me the start and stop buttons

**Comment by OscarBeiro** [comment]
Hi,
Please check out the quick manual: https://tic.gal/en/project/actualtime-plugin-glpi/
I think you need a task to track time. 
Ticket creation is not a valid event for that. You already have the SLA - TTO and TTR to track ticket life span.
Regards,
