### ISSUE TITLE
Align the timer laucher on 10.0.10

### ISSUE THREAD

**Issue by gitsyncuser** [ticgal/actualtime#122]
<p>New GLPI version has altered the width of the right column on ticket tasks.</p>\n<p><a href=\"/front/document.send.php?docid=48127&itemtype=Ticket&items_id=17545\" target=\"_blank\" ><img alt=\"4ac471c2-e509fb39-65141450115072.89342884\" width=\"881\" src=\"/front/document.send.php?docid=48127&itemtype=Ticket&items_id=17545\" /></a></p>\n<p>We should align the Actualtime toggle.</p>\n<p>Consider if the next release should be limited to 10.0.10 and above.</p><blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_17545' rel='nofollow'>17545</a><br>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by OscarBeiro** [comment]
Fixed on 2.2
