### ISSUE TITLE
Error when trying to install v2.2.0 on glpi 10.0.11

### ISSUE THREAD

**Issue by phamorais** [ticgal/actualtime#124]
Hi Guys

When trying to install plugin on GLPI 10.0.11 I am receiving the error below

![image](https://github.com/ticgal/actualtime/assets/35368369/9a61aa03-2866-42b9-b825-e5b2559d23ff)

**Comment by OscarBeiro** [comment]
Could you provide additional info? We cannot reproduce.

1. Previous ActualTime version? 
1. GLPI version?
2.  Could you provide the system info?
3. Steps to reproduce

Thanks

**Comment by OscarBeiro** [comment]
Update to 3.0.0 and return if needed.

**Comment by jcervantes-sipecom** [comment]
Same error here:

> 2.2.0 multiple alter in glpi_plugin_actualtime_tasks - Error durante el query a la base de datos: ALTER TABLE `glpi_plugin_actualtime_tasks` CHANGE `origin_end` `origin_end` INT NOT NULL DEFAULT '0' - Error is Invalid default value for 'override_begin'

I'm on GLPI 10.0.11 and trying to update from 2.2.0 to 3.0.0

![image](https://github.com/ticgal/actualtime/assets/56606032/12c7302b-559d-4bc6-8bd4-f7a946a6e928)

Same as: https://github.com/ticgal/actualtime/issues/127

**Comment by jcervantes-sipecom** [comment]
The only solution I tried was: 

1. backup actualtime tables and records, 
2. then uninstalled actualtime, making sure that the actualtimes was deleted or manually deleting, 
3. then deleted the actualtime folder, 
4. downloaded the last version and install it, 
5. restore the records previously backed up but inserting the value `TicketTask` in the new column `itemtype` in all records, and saving.
6. Then I could install the last 3.0.0 version

Also I check out that some Columns have different default value that my previous version has:
![image](https://github.com/ticgal/actualtime/assets/56606032/99ef18d3-cf64-404a-a06a-2367299be5ce)
