### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by oxedgar** [ticgal/actualtime#125]
Hello,

Thanks for your plugin it is verry good for us each day! 
So can you pls add any feature to automaticly synchronise time counted by the plugin directly on the time passed in glpi? peraps this feature allow to work with statistics of glpi more fine!?!

And we search any way to make one report by ticket when my customer demand it! can you tell me how i can take that in glpi?

**Comment by OscarBeiro** [comment]
This is a feature that already exists: Automatically update the duration
https://tic.gal/glpi/glpi-plugins/actualtime-the-time-tracking-plugin-for-glpi/

You have widgets, and reports are tricky in GLPI. We can build something if you need it. Please let us know through our website.
Regards,
