### ISSUE TITLE
Error tras actualizar a GLPI 10.0.11

### ISSUE THREAD

**Issue by BlackBitUser** [ticgal/actualtime#127]
Cambio de la estructura de la base de datos - glpi_plugin_actualtime_configs (0 seconds)

Cambio de la estructura de la base de datos - glpi_plugin_actualtime_tasks (0 seconds)

2.2.0 multiple alter in glpi_plugin_actualtime_tasks - Error durante la consulta a la base de datos: ALTER TABLE `glpi_plugin_actualtime_tasks` CHANGE `origin_end` `origin_end` INT NOT NULL DEFAULT '0' , ADD `override_begin` TIMESTAMP , ADD `override_end` TIMESTAMP - Error Invalid default value for 'override_begin'

;-----< SERVER >-----
Operating system: Windows NT TLKSWINGLPI 10.0 build 17763 (Windows Server 2019) AMD64
PHP 8.1.10 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, readline, session, sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="120" memory_limit="512M" post_max_size="40M" safe_mode="" session.save_handler="files"
	upload_max_filesize="40M" disable_functions="" 
Software: Apache/2.4.54 (Win64) OpenSSL/1.1.1p PHP/8.1.10 (Apache/2.4.54 (Win64) OpenSSL/1.1.1p PHP/8.1.10 Server at
	support.lksnext.com Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.4.25-MariaDB
	Server SQL Mode: NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/GLPIECOTIC
	Host info: localhost via TCP/IP
	
PHP version (8.1.10) is supported.PHP version (8.1.10) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.4.25) is supported.Database engine version (10.4.25) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to C:\xampp\htdocs/files/_cache has been validated. Write access to C:\xampp\htdocs/files/_cron has been validated. Write access to C:\xampp\htdocs/files has been validated. Write access to C:\xampp\htdocs/files/_dumps has been validated. Write access to C:\xampp\htdocs/files/_graphs has been validated. Write access to C:\xampp\htdocs/files/_lock has been validated. Write access to C:\xampp\htdocs/files/_pictures has been validated. Write access to C:\xampp\htdocs/files/_plugins has been validated. Write access to C:\xampp\htdocs/files/_rss has been validated. Write access to C:\xampp\htdocs/files/_sessions has been validated. Write access to C:\xampp\htdocs/files/_tmp has been validated. Write access to C:\xampp\htdocs/files/_uploads has been validated.Write access to C:\xampp\htdocs/files/_cache has been validated.
Write access to C:\xampp\htdocs/files/_cron has been validated.
Write access to C:\xampp\htdocs/files has been validated.
Write access to C:\xampp\htdocs/files/_dumps has been validated.
Write access to C:\xampp\htdocs/files/_graphs has been validated.
Write access to C:\xampp\htdocs/files/_lock has been validated.
Write access to C:\xampp\htdocs/files/_pictures has been validated.
Write access to C:\xampp\htdocs/files/_plugins has been validated.
Write access to C:\xampp\htdocs/files/_rss has been validated.
Write access to C:\xampp\htdocs/files/_sessions has been validated.
Write access to C:\xampp\htdocs/files/_tmp has been validated.
Write access to C:\xampp\htdocs/files/_uploads has been validated.

Web server root directory configuration seems safe.Web server root directory configuration seems safe.
Sessions configuration is secured.Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is not present.Zend OPcache extension is not present.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\xampp\htdocs/marketplace has been validated.Write access to C:\xampp\htdocs/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

;-----< GLPI constants >-----
GLPI_ROOT: "C:\\xampp\\htdocs"
GLPI_CONFIG_DIR: "C:\\xampp\\htdocs/config"
GLPI_VAR_DIR: "C:\\xampp\\htdocs/files"
GLPI_MARKETPLACE_DIR: "C:\\xampp\\htdocs/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "C:\\xampp\\htdocs/files"
GLPI_CACHE_DIR: "C:\\xampp\\htdocs/files/_cache"
GLPI_CRON_DIR: "C:\\xampp\\htdocs/files/_cron"
GLPI_DUMP_DIR: "C:\\xampp\\htdocs/files/_dumps"
GLPI_GRAPH_DIR: "C:\\xampp\\htdocs/files/_graphs"
GLPI_LOCAL_I18N_DIR: "C:\\xampp\\htdocs/files/_locales"
GLPI_LOCK_DIR: "C:\\xampp\\htdocs/files/_lock"
GLPI_LOG_DIR: "C:\\xampp\\htdocs/files/_log"
GLPI_PICTURE_DIR: "C:\\xampp\\htdocs/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "C:\\xampp\\htdocs/files/_plugins"
GLPI_RSS_DIR: "C:\\xampp\\htdocs/files/_rss"
GLPI_SESSION_DIR: "C:\\xampp\\htdocs/files/_sessions"
GLPI_TMP_DIR: "C:\\xampp\\htdocs/files/_tmp"
GLPI_UPLOAD_DIR: "C:\\xampp\\htdocs/files/_uploads"
GLPI_INVENTORY_DIR: "C:\\xampp\\htdocs/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "C:\\xampp\\htdocs/locales"
GLPI_VERSION: "10.0.11"
GLPI_SCHEMA_VERSION: "10.0.11@6795e1eea6621428b5ef42350d555715bda8a96f"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2023"

;-----< Libraries >-----
htmlawed/htmlawed version 1.2.14 in (C:\xampp\htdocs\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.8.0 in (C:\xampp\htdocs\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\xampp\htdocs\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.6.2 in (C:\xampp\htdocs\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\xampp\htdocs\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\xampp\htdocs\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\xampp\htdocs\vendor\iamcal\lib_autolink)
sabre/dav in (C:\xampp\htdocs\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\xampp\htdocs\vendor\sabre\http\lib)
sabre/uri in (C:\xampp\htdocs\vendor\sabre\uri\lib)
sabre/vobject in (C:\xampp\htdocs\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\xampp\htdocs\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\xampp\htdocs\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\xampp\htdocs\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\xampp\htdocs\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\xampp\htdocs\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\xampp\htdocs\vendor\elvanto\litemoji\src)
symfony/console in (C:\xampp\htdocs\vendor\symfony\console)
scssphp/scssphp in (C:\xampp\htdocs\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\xampp\htdocs\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\xampp\htdocs\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\xampp\htdocs\vendor\rlanvin\php-rrule\src)
ramsey/uuid in (C:\xampp\htdocs\vendor\ramsey\uuid\src)
psr/log in (C:\xampp\htdocs\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\xampp\htdocs\vendor\psr\simple-cache\src)
psr/cache in (C:\xampp\htdocs\vendor\psr\cache\src)
league/csv in (C:\xampp\htdocs\vendor\league\csv\src)
mexitek/phpcolors in (C:\xampp\htdocs\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\xampp\htdocs\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\xampp\htdocs\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\xampp\htdocs\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\xampp\htdocs\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\xampp\htdocs\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\xampp\htdocs\vendor\symfony\cache)
html2text/html2text in (C:\xampp\htdocs\vendor\html2text\html2text\src)
symfony/css-selector in (C:\xampp\htdocs\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\xampp\htdocs\vendor\symfony\dom-crawler)
twig/twig in (C:\xampp\htdocs\vendor\twig\twig\src)
twig/string-extra in (C:\xampp\htdocs\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (C:\xampp\htdocs\vendor\symfony\polyfill-php82)
league/oauth2-client in (C:\xampp\htdocs\vendor\league\oauth2-client\src\Provider)
league/oauth2-google in (C:\xampp\htdocs\vendor\league\oauth2-google\src\Provider)
thenetworg/oauth2-azure in (C:\xampp\htdocs\vendor\thenetworg\oauth2-azure\src\Provider)

**Comment by OscarBeiro** [comment]
Test with 3.0.0 and reopen if needed.

**Comment by jcervantes-sipecom** [comment]
Same error here:

> 2.2.0 multiple alter in glpi_plugin_actualtime_tasks - Error durante el query a la base de datos: ALTER TABLE `glpi_plugin_actualtime_tasks` CHANGE `origin_end` `origin_end` INT NOT NULL DEFAULT '0' - Error is Invalid default value for 'override_begin'

I'm on GLPI 10.0.11 and trying to update from 2.2.0 to 3.0.0

![image](https://github.com/ticgal/actualtime/assets/56606032/12c7302b-559d-4bc6-8bd4-f7a946a6e928)
