### ISSUE TITLE
Actualtime doesn't update the planned period value

### ISSUE THREAD

**Issue by jussara-ti** [ticgal/actualtime#129]
Hello,

I've found a problem while using the Actualtime plugin

**GLPI version:** 10.0.11
**Actualtime version:** 3.0.0

Since version 10.0.11 of GLPI, the duration and planned period fields have been bidirectionally linked in planned tasks (using the "Plan this task" button). This means that both fields always load the same value, and if one is modified, the other is also modified.

Problem: Whenever I complete a planned task by clicking on its checkbox, the Actualtime changes the duration field of the task, but does not change the planned period field. This shouldn't be a problem, but if the task is edited while being completed, the duration of the task reverts to marking the same duration as the planned period field (which was not changed), overwriting the previous change made by Actualtime. Whenever I click on the save button after editing a completed task, the planned period field replaces the duration time added previously by Actualtime.

Moreover, if the task is completed within its editing interface (by clicking on the Actualtime stop button) the duration field will instantly get the Actualtime tracked time, but after clicking on the "save" button, the duration field will get the planned period field value, making it seem like Actualtime did not work and did not fill in the duration field.

This bug becomes more evident now that Actualtime also works on changes, as the total duration of the change depends on the duration of the tasks.

The expected behavior is for the planned period field to be changed to the same value that Actualtime inserts into the task duration field.

Step-by-Step reproduction of the bug:

Creating the planned task and setting the planned period to 10 minutes, activating the actualtime counter and adding the task:
![img1](https://github.com/ticgal/actualtime/assets/60328341/23fd3e9e-5948-4e6f-b980-0321f5179de3)

Completing the task:
![img2](https://github.com/ticgal/actualtime/assets/60328341/855500a0-587e-4c74-b893-5b556d3e2e37)

After refreshing the page, the task duration field is updated, but the planned period stays the same as before:
![img3](https://github.com/ticgal/actualtime/assets/60328341/31ef5ba9-1ed5-4fdd-b281-da189019e4aa)

So far, the total duration of the change is correct: 
![img4](https://github.com/ticgal/actualtime/assets/60328341/bb9c246d-a17c-49bc-ace1-5da69b99eb53)

If I edit and save the completed task, the task duration field is updated again, now it has the same value as the planned period and it’s different from the actualtime value: 
![img5](https://github.com/ticgal/actualtime/assets/60328341/027bd8cb-5f5f-411d-a2be-b476508957b8)

The total duration of the Change is also updated:
![img6](https://github.com/ticgal/actualtime/assets/60328341/b5169e30-48df-4dfb-8199-0a974f01197d)

In this next example I’ll be creating another task in another Change the same way I created the one above, except I’ll be setting the planned period to 20 minutes

Completing the planned task from the editing interface:
![img7](https://github.com/ticgal/actualtime/assets/60328341/8c0d9991-4076-4450-b235-b6e300996920)

After saving, the duration of the task and total duration of the change match the planned period and not the Actualtime value:
![img8](https://github.com/ticgal/actualtime/assets/60328341/8ac202c1-46a6-49cd-9292-f1f4a5f51e45)
![img9](https://github.com/ticgal/actualtime/assets/60328341/5067f731-a146-43dc-b50a-34f571166527)

**Comment by OscarBeiro** [comment]
Please share your Actualtime Settings.

**Comment by jussara-ti** [comment]
Hello, here it is

![image](https://github.com/ticgal/actualtime/assets/60328341/98cb4b85-7e6d-4b8a-ab9b-81afba5e57a8)

**Comment by OscarBeiro** [comment]
I'm sorry. I think I read your issue too quickly and didn't get it.
In our opinion, updating the planned duration doesn't make sense. Planned is almost the opposite of Actual.
So, planned duration should stick to the time scheduled for a certain task. It makes sense that duration is updated with a real or near-real one, so you can compare both and watch for significant deviations.

Regards,

**Comment by jussara-ti** [comment]
Got it... I suggested to update the planned period value but this wouldn't be the only solution. 

My main problem is that if I edit a completed task that is planned, the task duration is replaced by the planned duration, erasing the actualtime value that was placed there when the task was first completed.
Other solution, that will not change the planned value, is to make the actualtime value always have priority against the planned duration to fill the task duration field when a task is edited.

What do you think?

Thanks for the attention.
