### ISSUE TITLE
When installing new after deleting it on disk.

### ISSUE THREAD

**Issue by BlackBitUser** [ticgal/actualtime#132]
Cambio de la estructura de la base de datos - glpi_plugin_actualtime_configs (0 seconds)

Cambio de la estructura de la base de datos - glpi_plugin_actualtime_tasks (1 segundos)

3.0.0 multiple alter in glpi_plugin_actualtime_tasks - Error durante la consulta a la base de datos: ALTER TABLE `glpi_plugin_actualtime_tasks` CHANGE `origin_end` `origin_end` INT NOT NULL DEFAULT '0' , ADD `override_begin` TIMESTAMP , ADD `override_end` TIMESTAMP , ADD `itemtype` varchar(255) NOT NULL AFTER `id` - Error Invalid default value for 'override_begin'

**Comment by BlackBitUser** [comment]
GLPI 10.0.11

**Comment by BlackBitUser** [comment]
Updated GLPI to version 10.0.14 and it doesn't install either.

**Comment by OscarBeiro** [comment]
We cannot reproduce the error.
We have updated the 2.2.0 to 3.0.0 without issue.

**Comment by phamorais** [comment]
Hi Guys @OscarBeiro 
We trying to update to 2.2.0 to 3.0.0 in GLPI 10.0.14 and receive de same error:

_Change of the database layout - glpi_plugin_actualtime_configs (0 seconds)

Change of the database layout - glpi_plugin_actualtime_tasks (0 seconds)

3.0.0 multiple alter in glpi_plugin_actualtime_tasks - Error during the database query: ALTER TABLE `glpi_plugin_actualtime_tasks` CHANGE `origin_end` `origin_end` INT NOT NULL DEFAULT '0' , ADD `itemtype` varchar(255) NOT NULL AFTER `id` - Error is Invalid default value for 'override_begin'_

https://github.com/ticgal/actualtime/assets/35368369/7e685fde-d0f7-47ad-b669-477546d8d171

**Comment by OscarBeiro** [comment]
Please check 3.0.1 and let us know if it fixes the issue.
Regards,
