### ISSUE TITLE
Create plugin settings on database

### ISSUE THREAD

**Issue by Multiconecta** [ticgal/actualtime#14]
Dismembering enhancement issue #4.

This issue will address the need of plugin configuration form and database table for any settings of plugin. Then, it will be possible to include new enhancements with specific settings to enable, assuring the initial normal behavior if no settings are enabled.

As will be needed at least one setting, the project should have an "Enable timer in tasks", default enabled, that will just deactivate all hooks (and the plugin) if set to Disable.

**Comment by OscarBeiro** [comment]
Great!
I think it would be better to remove this setting when we have a useful one, to avoid having a useless plugin if it is correctly installed and activated.

**Comment by Multiconecta** [comment]
Perfect. I'm on it. I'll let the config fork commented out after successful tests, so no settings will appear.

**Comment by Multiconecta** [comment]
I think I have it. But I would like to know how would be better to have those settings:
1) in a tab inside Setup - General (the same as Behaviours Plugin, for example)
2) in its own settings page (the same as Additional Fields Plugin, for example)

The settings page/tab would be accessed by clicking Setup - Plugins - ActualTime (as all plugins are). We can also add a menu item (probably in menu Assistance), case we choose option 2 above. Additional Plugins, for instance, adds its settings menu in Setup menu. I think this would not make too much sense if plugin's settings in a tab inside general setup (option 1 above).

My opinion: as there aren't many settings planned, and it will be usually "one time configure" settings, I would choose option 1, with no menu item. But I would like your opinions.

**Comment by OscarBeiro** [comment]
As you wish.
It's OK option 1.

**Comment by Multiconecta** [comment]
The settings are ready. I just don't know if it shouldn't be pulled to a test branch, so you can see it working. Then, we just modify it to not work until an actual setting is necessary. Today, there is only the "Enable timer on tasks", that would disable all hooks (all plugin work) if not on. If you prefer, I can do the PR now (there is a "Enable timer on task" option in general setup, but disabling it save the option in the database and just do nothing).

**Comment by OscarBeiro** [comment]
Good idea.
Please, go ahead

**Comment by Multiconecta** [comment]
Oscar, I did not understand. Do you want me to create a pull request to master branch, with no action, or will you create a new branch, so I can create a pull request to that branch, for testing purposes?

**Comment by OscarBeiro** [comment]
Sorry, about the misunderstanding.
We had a development branch, but it was left behind a few commits.
A new development branch has been created, please create your PR to it.
Regards,

**Comment by Multiconecta** [comment]
Created PR #19 on branch development, for testing purposes. Only settings avaiable: enable or disable timer.

For Glpi to update the database, the plugin version was increase to 1.1.1. That way, updating plugin directory will show the upgrade option on Setup - Plugins page, needed to get the database change. No timer's data for the tasks will be lost.

**Comment by OscarBeiro** [comment]
OK. We had a warning before upgrade, but we couldn't reproduce. 
So , please, move on.
Obrigado

**Comment by Multiconecta** [comment]
Didn't get it? Clicking Upgrade in Setup-Plugins, you've got a warning? I didn't have any of these.

Just "git checkout development"
Glpi: Setup - Plugins, Upgrade, Enable
After that, you can reach the settings form clicking on "ActualTime" in the plugins page. Or directly in Setup-General, tab "ActualTime".

**Comment by OscarBeiro** [comment]
Don't worry. It's merged because It's working.
I told you we couldn't reproduce.

So should we close this issue, or do you want to keep working on it?

**Comment by Multiconecta** [comment]
We can close it. So we use the development branch for all the changes that will use the settings (that will probably come on 1.2.0). That way, no one using the plugin now need to upgrade and will do so only on the 1.2.0 release, but we can develop the features that need the settings.
