### ISSUE TITLE
Add a pause buttom

### ISSUE THREAD

**Issue by OscarBeiro** [ticgal/actualtime#17]
Originally asked by: João Gustavo Rudek
https://www.youtube.com/watch?v=Z2LbDOiKWaY&t=94s

Add a pause buttom alternative to stop buttom.
It would work same as stop, but without changing ticket status.

**Comment by Multiconecta** [comment]
@OscarBeiro , I am making some tests on that also. Currently you can stop the timer, the task automatically changes to "Done" and no more action buttons are available. You must close the task, change its status to "To do" and open it again. Then, the "Start" button appears again to begin a new timer period.

The idea probably is: a "Pause" button would just finish that period in the timer, but task would still be in "To do" status and something like a "Restart" button would appear, to start a new period. The "Stop" would probably be available to, even in paused state, so we can conclude the task (not sure on that one).

**Comment by OscarBeiro** [comment]
I agree with you.
Stop buttom its not compulsory, but seems a good focus all the task time management on the plugin.

A rough desygn could be:

![actualtime-3](https://user-images.githubusercontent.com/18396050/52867706-ce94bc00-3141-11e9-80a9-b28cd302610a.png)
![actualtime-4](https://user-images.githubusercontent.com/18396050/52867707-cf2d5280-3141-11e9-9f25-22da73fc73cc.png)
I've used the **start** string to avoid creating a new one, could be restart as well.

Obrigado

**Comment by Multiconecta** [comment]
> A rough desygn could be:
> 
> ![actualtime-4](https://user-images.githubusercontent.com/18396050/52867707-cf2d5280-3141-11e9-9f25-22da73fc73cc.png)
> I've used the **start** string to avoid creating a new one, could be restart as well.

@OscarBeiro , did you draw the buttons by yourself, or did you make a real form inside Glpi? I tried to  create two buttons but did not get a nice design as your example, both inside last column. I don't know too much about Glpi design, so just copied your current button to get two. They get too wide to fit in the last column in html table.

**Comment by xacobofg** [comment]
@Multiconecta This would be my method to add the second button.

```
if (self::checkTimerActive($item->getID())) {
   $value=__("End");
   $action="end";
   $color="red";
   $btnpause=true;
 } else {
   $value=__("Start");
   $action="start";
   $color="green";
   $btnpause=false;
}
$html="<tr class='tab_bg_2'>";
$html.="<td colspan='2'></td>";
$html.="<td colspan='2'>";
$html.="<div><input type='button' id='actualtime$rand' name='update' task_id='".$item->getID()."'action='".$action."' value='".$value."' class='x-button x-button-main' style='background-color:".$color.";color:white'></div>";
if ($btnpause) {
   $html.="<div><input type='button' id='actualtime$rand' name='update' task_id='".$item->getID()."'action='pause' value='".__("Pause")."' class='x-button x-button-main' style='background-color:orange;color:white'></div>";
}
$html.="</td></tr>";
```
But if you think of a better solution, you can add it.

**Comment by Multiconecta** [comment]
I'm working in this one. But please, can you help me with this git doubt? Should I create modifications to include Pause Button from the master or from the development branch. As there is no settings needed to address this issue, it could be merged directly to master, as we've been doing so far. But I am not sure what is the policy here.

**Comment by xacobofg** [comment]
You can create the pull request on the development branch

**Comment by Multiconecta** [comment]
I've got it working in [pausebutton branch](https://github.com/Multiconecta/actualtime/tree/pausebutton). Sent PR #23 (should wait for the pending PR in 'development' before sending? I'm not sure how it works).

**Comment by OscarBeiro** [comment]
Thank you.
