### ISSUE TITLE
Multiple timer pop-ups sometimes, sometimes, no pop-up at all

### ISSUE THREAD

**Issue by Multiconecta** [ticgal/actualtime#24]
Timer pop-ups are in post-item hook, so it does not pop in pages with no item listing, and pops multiple times in pages with multiple items list. There isn't really a hook that is triggered once (and only once) every page (actually there is one, but it is before any output and sending a javascript block there will yield errors in browsers.

I think it is possible to include a javascript code every page (add-javascript hook includes it on footer). From there, it would be possible to call 'count' action via ajax and include pop-up message. Never tested, but that could work, in my opinion.

**Comment by OscarBeiro** [comment]
We are aware of this issue, thank you.
As you've said, the hook is apparently triggered once for every task, and we haven't found an alternative working solution.
Your workaround could be OK. Let's try.

**Comment by OscarBeiro** [comment]
Good job.
Thanks
