### ISSUE TITLE
Null task follow up

### ISSUE THREAD

**Issue by boscorelly** [ticgal/actualtime#27]
Hi,

when i create a follow up, it also creates a timer with null values as begin/end time.

**Comment by OscarBeiro** [comment]
Could you post a screenshot and your GLPI install and plugin versions?

**Comment by boscorelly** [comment]
It was a false positive, a mistake when reading table datas.

**Comment by Multiconecta** [comment]
> Hi,
> 
> when i create a follow up, it also creates a timer with null values as begin/end time.

Aren't you using my version to open edit window automatically after opening a task. I actually create that record for telling the plugin that the edit window should be opened. The record should be deleted immediately, but maybe can be some uncommon situation when it does not (disconnection or something else). The alternative would be another table just for that, but it seemed too much for too little. That null-null timer would not be used anyway if, in some situation, it is not automatically deleted.
