### ISSUE TITLE
the counter not start

### ISSUE THREAD

**Issue by danielqb** [ticgal/actualtime#45]
when the actualtime_pressedButton is excecuted:
```
{"mensage":"Timer started","title":"Information","class":"info_msg","ticket_id":**false**,"time":0}
// if is pressed again
{"mensage":"**The task had not been** initialized","title":"Warning","class":"warn_msg"}
```

**In the function----------**
```
$(document).ready(function() {
   $("#actualtime_button_14_1_300687504").click(function(event) {
      actualtime_pressedButton(14, $(this).attr('action'));
   });
```

**the result is---------**
`result = {mensage: "Timer started", title: "Information", class: "info_msg", ticket_id: "1", time: 1297}`

**but the normal result is-------------**
`event = jQuery.Event {originalEvent: MouseEvent, type: "click", isDefaultPrevented: ƒ, timeStamp: 11906.424999999217, jQuery112407870046362835266:`

**Comment by OscarBeiro** [comment]
Hola Daniel :)

I don't get it. 
Please report glpi and plugin version.
Where do you get this results? Which log?
Thanks

**Comment by xacobofg** [comment]
Informations requested has not been provided.
