### ISSUE TITLE
Bug : can't stop timer

### ISSUE THREAD

**Issue by boscorelly** [ticgal/actualtime#5]
I started a timer, and when i tried to stop it i had the message : 
Information
Only the user who initiated the task can close it

**Comment by boscorelly** [comment]
GLPI 9.3.1
Plugin 1.1.0
no errors in logs...

**Comment by OscarBeiro** [comment]
Please check the data opened on glpi_plugins_actualtime_tasks.
Since this is no sensitive data, you could post it here.
We also need to know your user id and ticket id.

**Comment by OscarBeiro** [comment]
Apparently user 127 started the task.
Could you login with user 127, stop it, and make another test?

**Comment by boscorelly** [comment]
this user doesn't exist...

**Comment by OscarBeiro** [comment]
OK, then.
This is an issue we cannot reproduce, on our GLPI installations.

Some other plugin or custom code could be the cause. It's hard to know.

Please make a complete uninstall, and clean, and reinstall to check for some installation errors, and test with other user (not 153).
Do you have a test instance or a clean install to test it?

**Comment by boscorelly** [comment]
for now no, but i will make a test platform if needed.

i'll try with another user.

**Comment by OscarBeiro** [comment]
Hi @boscorelly 
It seems clear this issue is related with your particular GLPI installation.
Please make a test environment, and we will reopen if you can reproduce the same issue.
