### ISSUE TITLE
ticket duration display

### ISSUE THREAD

**Issue by boscorelly** [ticgal/actualtime#53]
<p><a href="https://github.com/ticgal/actualtime/issues/53">https://github.com/ticgal/actualtime/issues/53</a></p><p>Hi,</p><p>as a super-admin, when i look at the ticket time, i don't see the time i set manually. I only see the time count by the plugin.</p><p>Is it managed by a file in the plugin ? (so i can try to fix this)</p><p><br />Created by boscorelly</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_2303' rel='nofollow'>2303</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Beiro Óscar (14)</blockquote>

**Comment by boscorelly** [comment]
it can be there : getSpecificValueToDisplay ?

https://github.com/ticgal/actualtime/blob/development/inc/task.class.php

**Comment by OscarBeiro** [comment]
Hi @boscorelly,

I don't understand.  Could you post some screenshot?

**Comment by boscorelly** [comment]
Here is a view of the ticket :
![image](https://user-images.githubusercontent.com/3873787/67392497-ed850100-f5a0-11e9-806e-a1a28da95387.png)

when editing :
![image](https://user-images.githubusercontent.com/3873787/67392743-63896800-f5a1-11e9-89eb-313d223a54a8.png)

**Comment by boscorelly** [comment]
disabling actual time change nothing.

no errors in debug mode, and no error in logs...

the time set manually is correctly diaplayd in tickets list :(

**Comment by OscarBeiro** [comment]
If you disable actualtime and nothing changes, this is not related with our plugin.
I close.

**Comment by boscorelly** [comment]
i have tried with all others addons disabled, and is it the same

the problem is : if i start a counter and time is found in database, so the time is displayed. If not, nothing is displayed event if i manually set a duration for the ticket.
