### ISSUE TITLE
When more than one tech, Total duration is wrong

### ISSUE THREAD

**Issue by OscarBeiro** [ticgal/actualtime#60]
Check attached image from internal: 2088 
![image](https://user-images.githubusercontent.com/18396050/71258947-9d73b200-2337-11ea-84b2-9f46c8d5928b.png)

**Comment by gitsyncuser** [comment]
<p>May be related to:</p><p><a href=\"https://github.com/glpi-project/glpi/commit/109b1f2e490c4f495d345abd2250b8a98202c841\">https://github.com/glpi-project/glpi/commit/109b1f2e490c4f495d345abd2250b8a98202c841</a></p><blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Beiro Óscar</blockquote>
