### ISSUE TITLE
Ya esta realizando una tarea Petición.

### ISSUE THREAD

**Issue by graus69** [ticgal/actualtime#61]
<a href='https://github.com/ticgal/actualtime/issues/61'>https://github.com/ticgal/actualtime/issues/61</a><br><p>Cuando intento inicar el cronometro de una petición me muestra el siguiente error "Ya se esta realizando una tarea Petición".nHe intentado reproducir el mismo error desde otro usuario y esto pasa cuando borras o cierras una peticion sin finalizar el cronometro, ya que no muestra la peticion que es dado que esta cerrrada o borrada se detener este error.</p>n<p>Un saludo.</p><br>Created by graus69
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_2826' rel='nofollow'>2826</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Xacobo Freire</blockquote>

**Comment by OscarBeiro** [comment]
Hola:
Gracias por notificarnos este problema.

Borrar tareas y tickets es una mala práctica, pero sin duda hay que tenerla en cuenta.
Como workaround, puedes evitar cerrar peticiones con el cronómetro en marcha, (bloqueando el cierre de tareas no finalizadas), utilizando Behaviors.

Saludos

**Comment by xacobofg** [comment]
Hola.
Esto ya esta solucionado #58 , saldrá en siguiente versión coincidiendo con la 9.5 de GLPI
