### ISSUE TITLE
9.5 compatibility

### ISSUE THREAD

**Issue by gitsyncuser** [ticgal/actualtime#70]
<p>Release a 9.5 compatible version:</p><ol><li>Support new GLPI marketplace</li></ol><blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_3812' rel='nofollow'>3812</a><br>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by cillox54** [comment]
Actualtime 1.3.0 don't work in GLPI 9.5.1

Update the plugin, when you want to activate it I get the following message: **This plugin requires GLPI >= 9.4.0 and <9.5**

**Comment by OscarBeiro** [comment]
Hi @cillox54,

We are aware, that's why the issue was opened :)

Regards,

**Comment by gitsyncuser** [comment]
Solution approved<blockquote>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>
