### ISSUE TITLE
Stop the task by accidental deletion

### ISSUE THREAD

**Issue by cillox54** [ticgal/actualtime#72]
<p><a href="https://github.com/ticgal/actualtime/issues/72">https://github.com/ticgal/actualtime/issues/72</a></p><p>If running time on the task <strong>accidentally eliminates</strong> the time doesn't stop, it keeps running and <strong>doesn't allow you to start another task.</strong> To stop this bug you have to change the <strong>null</strong> value in the completion record in the data base to stop this execution so that you can start another task with the same user.</p><p>This inconvenience happens little, but it has happened to different users of the system.</p><p><br />Created by cillox54</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_3902' rel='nofollow'>3902</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by OscarBeiro** [comment]
Hi,
This has been fixed on #47 even when purging tasks is not really a good practice.
Anyway, last version Actualtime  1.3.0 removes the timer at the same time the task is deleted.
Please upgrade, and, if the error persists, you will need to send us additional information: 
- Between [code] tags, Information about system installation and configuration at Setup > General > System
- php-errors.log 
- sql-errors.log
