### ISSUE TITLE
Erro no contador 

### ISSUE THREAD

**Issue by rafainpacto** [ticgal/actualtime#83]
Erro para contador do tempo durante as tarefas, GLPI 9.4.3 
Inicio a tarefa normalmente com o formulário padrão, inicio o contador após fazer alguma mudança e salvar o contador pega um horário bem diferente do que estava sendo contado. 
![Contador](https://user-images.githubusercontent.com/74738112/103767074-bdd3e480-4ffe-11eb-8c48-55d9c746af1b.PNG)

**Comment by OscarBeiro** [comment]
Olá Rafa,
We don't support previous versions. 
Please upgrade your GLPI to 9.5 and test latest release.
Regards,
