### ISSUE TITLE
Inconsistencia no timer active

### ISSUE THREAD

**Issue by soportesistemasbb** [ticgal/actualtime#85]
<p><a href="https://github.com/ticgal/actualtime/issues/85">https://github.com/ticgal/actualtime/issues/85</a></p><p>Buen día Tengo instalado glpi 9.5.4 y el plugin actualtime en lo cual al momento de crear, actualizar un ticket no me aparece activo este plugin y al revisar en la configuración la cual dejo en la imagen para lo cual necesitaría me ayudaran indicando cual podría ser la falla o problema del no funcionamiento. <img src="https://user-images.githubusercontent.com/82462350/114580310-5b653280-9c44-11eb-9d5a-be2d59f7c8c6.png" alt="imagen_2021-04-13_103946" /> <img src="https://user-images.githubusercontent.com/82462350/114580572-95363900-9c44-11eb-8d8c-72f27d75a919.png" alt="imagen_2021-04-13_104124" /></p><p><br />Creado por soportesistemasbb</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_5580' rel='nofollow'>5580</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by OscarBeiro** [comment]
Hi,

Please review this post. No relevant screenshots are been provided.
https://tic.gal/en/why-actualtime-doesnt-show-timer-buttons-on-tasks/

En el futuro por favor utiliza el inglés para recibir soporte, por favor.
Saludos

**Comment by soportesistemasbb** [comment]
Hi oscar at the moment to open issue is for in the configuration is active this options and any moment apear or activated the plugin if you can see the first picture look in all options are active.

**Comment by OscarBeiro** [comment]
Could you add a screenshot of a **saved to do task assigned to you?**

**Comment by soportesistemasbb** [comment]
Yes of course
![imagen_2021-04-13_110629](https://user-images.githubusercontent.com/82462350/114584251-1642ff80-9c48-11eb-8705-b01542b1abb3.png)
![imagen_2021-04-13_110643](https://user-images.githubusercontent.com/82462350/114584274-1e02a400-9c48-11eb-859e-1445e1446c93.png)

**Comment by OscarBeiro** [comment]
This is a **FOLLOWUP**, not a **TASK**. 
Time is tracked on ticket tasks, so does Actualtime.

Again, could you add a screenshot of a saved to do task assigned to you?

**Comment by soportesistemasbb** [comment]
ok in task its ok 
![imagen_2021-04-13_111719](https://user-images.githubusercontent.com/82462350/114585763-99188a00-9c49-11eb-84e8-c1cdfd825637.png)

**Comment by OscarBeiro** [comment]
Great.
That's the way to do it.
I close
