### ISSUE TITLE
Actualtime for GLPI v10 ?

### ISSUE THREAD

**Issue by Squikou** [ticgal/actualtime#88]
Hello,
Are you going to adapt the plugin to be compatible with GLPI 10?
Thanks in advance.

**Comment by OscarBeiro** [comment]
Hi,
Of course, we are.
Unfortunately, no ETD.
Regards

**Comment by Squikou** [comment]
Thank you for the quick reply.
We will be patient.

**Comment by JaderFarinon** [comment]
Hi,
any news about the new version for GLPI 10?

**Comment by MarchuckPL** [comment]
Hi,
Can i get any update about new version? If You are not pllaning to release it soon i need to downgrade GLPI. This plugin is critical for Us

**Comment by OscarBeiro** [comment]
Sorry about this, but you don't need to downgrade?
The official release of GLPI10 is tomorrow.
We have several priority developments, so it will have to wait until we start rolling the new version or some clients ask for this update.

You can also contribute a PR and we will review it.

Regards,

**Comment by infotelmonaco** [comment]
Hello, Any news on the compatibility or date of the release with GLPI 10 ? Please keep us up to date

**Comment by MarchuckPL** [comment]
Any updates ??

**Comment by OscarBeiro** [comment]
Hi, 
This summer is the better approach I can give you.
We will do our best to release it in July.

**Comment by OscarBeiro** [comment]
Hi, just to keep you updated.
We have been working on this, but there is a missing feature on GLPI 10 we need to show information like in GLPI 9.5
Teclib' is already aware of this. Unfortunately, we don't have an ETA from them.
Regards,

**Comment by MarchuckPL** [comment]
For me only thing we need is to be able to set date from past when creating tasks in ticket. And we need it really bad

**Comment by OscarBeiro** [comment]
Hi @MarchuckPL,
I really don't get what you mean, but if it is a new feature, you have to open another issue.
Regards,

**Comment by MarchuckPL** [comment]
Hi @OscarBeiro,
In version 9.5 with ActualTime i was able to change task creation date. Right now in v 10 when creating a task within ticket, task creation date is set to time when it is created and cannot be changed, i need to be able to modyfiy task creation date/time as it was possible with v9.5 with Your plugin, this is only feature I need
Regards,

**Comment by xacobofg** [comment]
Blocking issue https://github.com/glpi-project/glpi/issues/12025

**Comment by Squikou** [comment]
Hi,

Thanks a lot !

I just tested and during the installation, a blank page appears. If I refresh, nothing happened.

Screens :

***@***.***

>>

***@***.***

Thomas

De : Oscar B. ***@***.***>
Envoyé : mercredi 3 août 2022 15:45
À : ticgal/actualtime ***@***.***>
Cc : Squikou ***@***.***>; Author ***@***.***>
Objet : Re: [ticgal/actualtime] Actualtime for GLPI v10 ? (Issue #88)


Hi,
We have just released Actualtime 2 beta. Could you please test and report?
Thanks

**Comment by Squikou** [comment]
The error with debug mode : 

_PHP Compile Error (64): Access level to PluginActualtimeApirest::initEndpoint() must be protected (as in class Glpi\Api\API) or weaker in /var/www/glpi/plugins/actualtime/inc/apirest.class.php at line 187_

**Comment by OscarBeiro** [comment]
> The error with debug mode :
> 
> _PHP Compile Error (64): Access level to PluginActualtimeApirest::initEndpoint() must be protected (as in class Glpi\Api\API) or weaker in /var/www/glpi/plugins/actualtime/inc/apirest.class.php at line 187_
Thanks
#100

**Comment by JaderFarinon** [comment]
Fatal error: Access level to PluginActualtimeApirest::initEndpoint() must be protected (as in class Glpi\Api\API) or weaker in C:\inetpub\wwwroot\glpi\plugins\actualtime\inc\apirest.class.php on line 187

**Comment by OscarBeiro** [comment]
Sorry about it. Bad testing apparently :)
It's working on our side with Beta2

**Comment by JaderFarinon** [comment]
Hello, sorry.. I didn't pay attention to the new release of beta 2, the error no longer occurs in new release.
thanks!!

**Comment by OscarBeiro** [comment]
Beleça :)
Please test it and report back so that we can release the final version next week.

**Comment by alexandreti2018** [comment]
Hi,

A need plugin to run glpi 10.0.2.

I'not install with erro version 9.6.0?

help.

**Comment by OscarBeiro** [comment]
> Hi,
Hi,
 
> A need plugin to run GLPI 10.0.2.
Please test the Actualtime beta. Download it from the release section.
 
> I'not install with erro version 9.6.0?
I really don't understand this one. There is no 9.6 GLPI. 
> help.

**Comment by OscarBeiro** [comment]
Hopefully, this will be the last beta. We expect a release by the end of the week if nothing more is reported.
Regards,

**Comment by alexandreti2018** [comment]
> > Hi,
> 
> Hi,
> 
> > A need plugin to run GLPI 10.0.2.
> 
> Please test the Actualtime beta. Download it from the release section.
> 
> > I'not install with erro version 9.6.0?
> 
> I really don't understand this one. There is no 9.6 GLPI.
> 
> > help.

----------------------------------------------


Sorry,

I was running the wrong version.

**Comment by OscarBeiro** [comment]
It was finally released and will be available in the marketplace in a few minutes
