### ISSUE TITLE
Timer for more tasks together

### ISSUE THREAD

**Issue by evertondemoura** [ticgal/actualtime#99]
<p><a href="https://github.com/ticgal/actualtime/issues/99">https://github.com/ticgal/actualtime/issues/99</a></p><p>Hi all,</p><p>I would like to know if we can release the timer to work simultaneously on more than one task, ignoring the message "A user is already performing the task"?</p><p><br />Created by evertondemoura</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_10547' rel='nofollow'>10547</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by OscarBeiro** [comment]
Hi Everton,
I'm sorry but your requested feature goes against the plugin philosophy.
It is a tech time tracking tool and the tech should only work on one task at a time. 
Regards,
